language: cpp
sudo: false

services:
  - docker

jobs:
  include:
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="msat" OPTS="--auto-yes"
    - os: osx
      osx_image: xcode9
      env: SOLVER='btor' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='cvc4' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='msat' OPTS="--auto-yes"

script:
  # brew sometimes fails on something after the python installation -- but we don't want the build to fail
  - ./scripts/travis-setup-osx-python.sh || true
  # remove the python-dev installed from the apt
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       docker run -it -d --name manylinux --mount type=bind,source="$(pwd)"/../smt-switch,target=/smt-switch keyiz/manylinux-java /bin/bash
       docker exec -i manylinux -c "pip install pip install Cython==0.29 --install-option=--no-cython-compile"
       docker exec -i manylinux -c "cd /smt-switch && ./contrib/setup-${SOLVER}.sh ${OPTS}"
       docker exec -i manylinux -c "cd /smt-switch/build && make -j && make test"
       docker exec -i manylinux -c "cd /smt-switch/ && python contrib/wheels/build_wheel.py bdist_wheel"
       docker exec -i manylinux -c "cd /smt-switch && pip install pytest dist/* && pytest tests/"
    else
        sudo python3 -m pip install Cython==0.29 --install-option="--no-cython-compile"
        bash -c "./contrib/setup-${SOLVER}.sh ${OPTS}"
        bash -c "./configure.sh --${SOLVER} --python"
        bash -c "cd build && make -j && make test"
        # install wheels
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install wheel setuptools
        python3 contrib/wheels/build_wheel.py bdist_wheel
        bash -c "pip install pytest dist/* && cd tests && pytest ."
    fi

